- name: Instalar PHP e extensões
  apt:
    name:
      - php8.1
      - php8.1-cli
      - php8.1-fpm
      - php8.1-mbstring
      - php8.1-xml
      - php8.1-curl
      - php8.1-zip
      - php8.1-mysql
      - php8.1-bcmath
      - php8.1-tokenizer
      - php8.1-ctype
      - php8.1-gd
    state: present

- name: Reiniciar PHP-FPM
  systemd:
    name: php8.1-fpm
    state: restarted
    enabled: yes

- name: Instalar Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
